name: Check Ticket Prices

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour at minute 0
  workflow_dispatch:      # Optional: allows manual run from GitHub

jobs:
  check_prices:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11  # or your preferred Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps chromium

      - name: Upload screenshot
        uses: actions/upload-artifact@v4
        with:
          name: page-screenshot
          path: screenshot.png
          retention-days: 1

      - name: Run script
        env:
          EVENT_URL: ${{ secrets.EVENT_URL }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          python main.py